### ISSUE TITLE
[Bug]: No Screens Found Error after Nvidia 530.41.03

### ISSUE THREAD

**Issue by sfxworks** [Steam-Headless/docker-steam-headless#44]
### Describe the Bug

I've switched steam headless from some old Nvidia 1070s to newer Nvidia A2000s. Getting this error now. I've tried plugging in displays as a test. Honestly one cable may be bad, so waiting on fake dongles. Though I thought it could run headless?

### Steps to Reproduce

1. Run steam headless with Nvidia a2000
2. Watch it startup

### Expected Behavior

X starts

### Version

Build: [2023-06-24 03:10:18] [master] [6a2d55196b5253fef520ca883391d783716b4d06]

### Platform

docker
6.1.35-1-lts
530
k8s with nvidia container toolkit

### Relevant log output

```Shell
X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: linux Debian
Current Operating System: Linux epyc-gigabyte 6.1.35-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 15:54:02 +0000 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-linux-lts root=UUID=5a04216e-d5fa-4737-971f-db34ed7c2552 rw loglevel=3 quiet
Build Date: 23 March 2023  10:25:56AM
xorg-server 2:1.20.11-1+deb11u6 (https://www.debian.org/support)
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.55.log", Time: Sat Jun 24 05:55:05 2023
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/var/log/Xorg.55.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.

X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: linux Debian
Current Operating System: Linux epyc-gigabyte 6.1.35-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 15:54:02 +0000 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-linux-lts root=UUID=5a04216e-d5fa-4737-971f-db34ed7c2552 rw loglevel=3 quiet
Build Date: 23 March 2023  10:25:56AM
xorg-server 2:1.20.11-1+deb11u6 (https://www.debian.org/support)
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.55.log", Time: Sat Jun 24 05:55:07 2023
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/var/log/Xorg.55.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.

X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: linux Debian
Current Operating System: Linux epyc-gigabyte 6.1.35-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 15:54:02 +0000 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-linux-lts root=UUID=5a04216e-d5fa-4737-971f-db34ed7c2552 rw loglevel=3 quiet
Build Date: 23 March 2023  10:25:56AM
xorg-server 2:1.20.11-1+deb11u6 (https://www.debian.org/support)
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.55.log", Time: Sat Jun 24 05:55:09 2023
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/var/log/Xorg.55.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.




X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
[   371.789] Build Operating System: linux Debian
[   371.789] Current Operating System: Linux epyc-gigabyte 6.1.35-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 15:54:02 +0000 x86_64
[   371.789] Kernel command line: BOOT_IMAGE=/vmlinuz-linux-lts root=UUID=5a04216e-d5fa-4737-971f-db34ed7c2552 rw loglevel=3 quiet
[   371.789] Build Date: 23 March 2023  10:25:56AM
[   371.789] xorg-server 2:1.20.11-1+deb11u6 (https://www.debian.org/support)
[   371.789] Current version of pixman: 0.40.0
[   371.789]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[   371.789] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   371.789] (==) Log file: "/var/log/Xorg.55.log", Time: Sat Jun 24 05:55:48 2023
[   371.789] (==) Using config file: "/etc/X11/xorg.conf"
[   371.789] (==) Using config directory: "/etc/X11/xorg.conf.d"
[   371.789] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   371.790] (==) ServerLayout "Layout0"
[   371.790] (**) |-->Screen "Screen0" (0)
[   371.790] (**) |   |-->Monitor "Monitor0"
[   371.790] (**) |   |-->Device "Device0"
[   371.790] (**) |-->Input Device "Keyboard0"
[   371.790] (**) |-->Input Device "Mouse0"
[   371.790] (==) Automatically adding devices
[   371.790] (==) Automatically enabling devices
[   371.790] (==) Automatically adding GPU devices
[   371.790] (==) Max clients allowed: 256, resource mask: 0x1fffff
[   371.790] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   371.790]    Entry deleted from font path.
[   371.790] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        /usr/share/fonts/X11/100dpi/:unscaled,
        /usr/share/fonts/X11/75dpi/:unscaled,
        /usr/share/fonts/X11/Type1,
        /usr/share/fonts/X11/100dpi,
        /usr/share/fonts/X11/75dpi,
        built-ins
[   371.790] (==) ModulePath set to "/usr/lib/xorg/modules"
[   371.790] (WW) Hotplugging is on, devices using drivers 'kbd', 'mouse' or 'vmmouse' will be disabled.
[   371.790] (WW) Disabling Keyboard0
[   371.790] (WW) Disabling Mouse0
[   371.790] (II) Loader magic: 0x55c20c64ce40
[   371.790] (II) Module ABI versions:
[   371.790]    X.Org ANSI C Emulation: 0.4
[   371.790]    X.Org Video Driver: 24.1
[   371.790]    X.Org XInput driver : 24.1
[   371.790]    X.Org Server Extension : 10.0
[   371.790] (++) using VT number 7

[   371.790] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[   371.791] (II) xfree86: Adding drm device (/dev/dri/card1)
[   371.791] (II) xfree86: Adding drm device (/dev/dri/card2)
[   371.791] (II) xfree86: Adding drm device (/dev/dri/card0)
[   371.798] (--) PCI:*(129@0:0:0) 10de:2531:10de:151d rev 161, Mem @ 0xf2000000/16777216, 0x20030000000/268435456, 0x20040000000/33554432, I/O @ 0x00002000/128, BIOS @ 0x????????/524288
[   371.798] (--) PCI: (193@0:0:0) 10de:2531:10de:151d rev 161, Mem @ 0x9b000000/16777216, 0x18000000000/268435456, 0x18010000000/33554432, I/O @ 0x0000f000/128, BIOS @ 0x????????/524288
[   371.798] (--) PCI: (197@0:0:0) 1a03:2000:1458:1000 rev 65, Mem @ 0x98000000/33554432, 0x9a000000/131072, I/O @ 0x0000d000/128, BIOS @ 0x????????/131072
[   371.798] (II) LoadModule: "glx"
[   371.799] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   371.799] (II) Module glx: vendor="X.Org Foundation"
[   371.799]    compiled for 1.20.11, module version = 1.0.0
[   371.799]    ABI class: X.Org Server Extension, version 10.0
[   371.799] (II) LoadModule: "nvidia"
[   371.799] (II) Loading /usr/lib/xorg/modules/drivers/nvidia_drv.so
[   371.799] (II) Module nvidia: vendor="NVIDIA Corporation"
[   371.800]    compiled for 1.6.99.901, module version = 1.0.0
[   371.800]    Module class: X.Org Video Driver
[   371.800] (II) NVIDIA dlloader X Driver  535.54.03  Tue Jun  6 22:23:02 UTC 2023
[   371.800] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[   371.800] (II) Loading sub module "fb"
[   371.800] (II) LoadModule: "fb"
[   371.800] (II) Loading /usr/lib/xorg/modules/libfb.so
[   371.800] (II) Module fb: vendor="X.Org Foundation"
[   371.800]    compiled for 1.20.11, module version = 1.0.0
[   371.800]    ABI class: X.Org ANSI C Emulation, version 0.4
[   371.800] (II) Loading sub module "wfb"
[   371.800] (II) LoadModule: "wfb"
[   371.800] (II) Loading /usr/lib/xorg/modules/libwfb.so
[   371.800] (II) Module wfb: vendor="X.Org Foundation"
[   371.800]    compiled for 1.20.11, module version = 1.0.0
[   371.800]    ABI class: X.Org ANSI C Emulation, version 0.4
[   371.800] (**) NVIDIA(0): Depth 24, (--) framebuffer bpp 32
[   371.800] (==) NVIDIA(0): RGB weight 888
[   371.800] (==) NVIDIA(0): Default visual is TrueColor
[   371.800] (==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[   371.800] (**) NVIDIA(0): Option "ModeValidation" "NoMaxPClkCheck, NoEdidMaxPClkCheck, NoMaxSizeCheck, NoHorizSyncCheck, NoVertRefreshCheck, NoVirtualSizeCheck, NoExtendedGpuCapabilitiesCheck, NoTotalSizeCheck, NoDualLinkDVICheck, NoDisplayPortBandwidthCheck, AllowNon3DVisionModes, AllowNonHDMI3DModes, AllowNonEdidModes, NoEdidHDMI2Check, AllowDpInterlaced"
[   371.800] (**) NVIDIA(0): Option "ProbeAllGpus" "False"
[   371.800] (**) NVIDIA(0): Option "AllowEmptyInitialConfiguration" "True"
[   371.800] (**) NVIDIA(0): Option "ConnectedMonitor" "DFP"
[   371.800] (**) NVIDIA(0): Enabling 2D acceleration
[   371.800] (**) NVIDIA(0): ConnectedMonitor string: "DFP"
[   371.800] (II) Loading sub module "glxserver_nvidia"
[   371.800] (II) LoadModule: "glxserver_nvidia"
[   371.800] (II) Loading /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
[   371.806] (II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
[   371.806]    compiled for 1.6.99.901, module version = 1.0.0
[   371.806]    Module class: X.Org Server Extension
[   371.806] (II) NVIDIA GLX Module  535.54.03  Tue Jun  6 22:23:41 UTC 2023
[   371.806] (II) NVIDIA: The X server supports PRIME Render Offload.
[   371.942] (--) NVIDIA(0): Valid display device(s) on GPU-0 at PCI:129:0:0
[   371.942] (--) NVIDIA(0):     DFP-0
[   371.942] (--) NVIDIA(0):     DFP-1
[   371.942] (--) NVIDIA(0):     DFP-2
[   371.942] (--) NVIDIA(0):     DFP-3
[   371.942] (--) NVIDIA(0):     DFP-4
[   371.942] (--) NVIDIA(0):     DFP-5 (boot)
[   371.942] (--) NVIDIA(0):     DFP-6
[   371.942] (--) NVIDIA(0):     DFP-7
[   371.943] (**) NVIDIA(0): Using ConnectedMonitor string "DFP-0".
[   371.944] (II) NVIDIA(0): NVIDIA GPU NVIDIA RTX A2000 (GA106GL-A) at PCI:129:0:0
[   371.944] (II) NVIDIA(0):     (GPU-0)
[   371.944] (--) NVIDIA(0): Memory: 6285312 kBytes
[   371.944] (--) NVIDIA(0): VideoBIOS: 94.06.2c.00.01
[   371.944] (II) NVIDIA(0): Detected PCI Express Link width: 16X
[   371.953] (--) NVIDIA(GPU-0): DFP-0: connected
[   371.953] (--) NVIDIA(GPU-0): DFP-0: Internal DisplayPort
[   371.953] (--) NVIDIA(GPU-0): DFP-0: 2670.0 MHz maximum pixel clock
[   371.953] (--) NVIDIA(GPU-0):
[   371.953] (--) NVIDIA(GPU-0): DFP-1: disconnected
[   371.953] (--) NVIDIA(GPU-0): DFP-1: Internal TMDS
[   371.953] (--) NVIDIA(GPU-0): DFP-1: 165.0 MHz maximum pixel clock
[   371.953] (--) NVIDIA(GPU-0):
[   371.953] (--) NVIDIA(GPU-0): DFP-2: disconnected
[   371.953] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[   371.953] (--) NVIDIA(GPU-0): DFP-2: 2670.0 MHz maximum pixel clock
[   371.953] (--) NVIDIA(GPU-0):
[   371.953] (--) NVIDIA(GPU-0): DFP-3: disconnected
[   371.953] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[   371.953] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[   371.953] (--) NVIDIA(GPU-0):
[   371.953] (--) NVIDIA(GPU-0): DFP-4: disconnected
[   371.953] (--) NVIDIA(GPU-0): DFP-4: Internal DisplayPort
[   371.953] (--) NVIDIA(GPU-0): DFP-4: 2670.0 MHz maximum pixel clock
[   371.953] (--) NVIDIA(GPU-0):
[   371.953] (--) NVIDIA(GPU-0): DFP-5: disconnected
[   371.953] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[   371.953] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[   371.953] (--) NVIDIA(GPU-0):
[   371.953] (--) NVIDIA(GPU-0): DFP-6: disconnected
[   371.953] (--) NVIDIA(GPU-0): DFP-6: Internal DisplayPort
[   371.953] (--) NVIDIA(GPU-0): DFP-6: 2670.0 MHz maximum pixel clock
[   371.953] (--) NVIDIA(GPU-0):
[   371.953] (--) NVIDIA(GPU-0): DFP-7: disconnected
[   371.953] (--) NVIDIA(GPU-0): DFP-7: Internal TMDS
[   371.953] (--) NVIDIA(GPU-0): DFP-7: 165.0 MHz maximum pixel clock
[   371.953] (--) NVIDIA(GPU-0):
[   371.953] (**) NVIDIA(GPU-0): Mode Validation Overrides for DFP-0:
[   371.953] (**) NVIDIA(GPU-0):     NoMaxSizeCheck
[   371.953] (**) NVIDIA(GPU-0):     NoVirtualSizeCheck
[   371.953] (**) NVIDIA(GPU-0):     NoMaxPClkCheck
[   371.953] (**) NVIDIA(GPU-0):     NoEdidMaxPClkCheck
[   371.953] (**) NVIDIA(GPU-0):     NoHorizSyncCheck
[   371.953] (**) NVIDIA(GPU-0):     NoVertRefreshCheck
[   371.953] (**) NVIDIA(GPU-0):     NoExtendedGpuCapabilitiesCheck
[   371.953] (**) NVIDIA(GPU-0):     NoTotalSizeCheck
[   371.953] (**) NVIDIA(GPU-0):     NoDualLinkDVICheck
[   371.953] (**) NVIDIA(GPU-0):     NoDisplayPortBandwidthCheck
[   371.953] (**) NVIDIA(GPU-0):     AllowNon3DVisionModes
[   371.953] (**) NVIDIA(GPU-0):     AllowNonEdidModes
[   371.953] (**) NVIDIA(GPU-0):     AllowNonHDMI3DModes
[   371.953] (**) NVIDIA(GPU-0):     NoEdidHDMI2Check
[   371.953] (**) NVIDIA(GPU-0):     AllowDpInterlaced
[   371.954] (EE) NVIDIA(GPU-0): Unable to add conservative default mode "nvidia-auto-select".
[   371.954] (EE) NVIDIA(GPU-0): Unable to add "nvidia-auto-select" mode to ModePool.
[   371.954] (WW) NVIDIA(0): No valid modes for "DFP-0:1920x1080R"; removing.
[   371.954] (WW) NVIDIA(0):
[   371.954] (WW) NVIDIA(0): Unable to validate any modes; falling back to the default mode
[   371.954] (WW) NVIDIA(0):     "nvidia-auto-select".
[   371.954] (WW) NVIDIA(0):
[   371.954] (WW) NVIDIA(0): No valid modes for "DFP-0:nvidia-auto-select"; removing.
[   371.954] (EE) NVIDIA(0): Unable to use default mode "nvidia-auto-select".
[   371.954] (EE) NVIDIA(0): Failing initialization of X screen
[   372.086] (II) UnloadModule: "nvidia"
[   372.086] (II) UnloadSubModule: "glxserver_nvidia"
[   372.086] (II) Unloading glxserver_nvidia
[   372.086] (II) UnloadSubModule: "wfb"
[   372.086] (II) UnloadSubModule: "fb"
[   372.086] (**) NVIDIA(G0): Depth 24, (--) framebuffer bpp 32
[   372.086] (==) NVIDIA(G0): RGB weight 888
[   372.086] (==) NVIDIA(G0): Default visual is TrueColor
[   372.086] (==) NVIDIA(G0): Using gamma correction (1.0, 1.0, 1.0)
[   372.086] (**) NVIDIA(G0): Option "ProbeAllGpus" "False"
[   372.086] (**) NVIDIA(G0): Option "AllowEmptyInitialConfiguration" "True"
[   372.086] (**) NVIDIA(G0): Enabling 2D acceleration
[   372.086] (II) NVIDIA: The X server supports PRIME Render Offload.
[   372.275] (--) NVIDIA(0): Valid display device(s) on GPU-1 at PCI:193:0:0
[   372.275] (--) NVIDIA(0):     DFP-0
[   372.275] (--) NVIDIA(0):     DFP-1
[   372.275] (--) NVIDIA(0):     DFP-2
[   372.275] (--) NVIDIA(0):     DFP-3
[   372.275] (--) NVIDIA(0):     DFP-4
[   372.275] (--) NVIDIA(0):     DFP-5 (boot)
[   372.275] (--) NVIDIA(0):     DFP-6
[   372.275] (--) NVIDIA(0):     DFP-7
[   372.276] (II) NVIDIA(G0): NVIDIA GPU NVIDIA RTX A2000 (GA106GL-A) at PCI:193:0:0
[   372.276] (II) NVIDIA(G0):     (GPU-1)
[   372.276] (--) NVIDIA(G0): Memory: 6285312 kBytes
[   372.276] (--) NVIDIA(G0): VideoBIOS: 94.06.2c.00.01
[   372.276] (II) NVIDIA(G0): Detected PCI Express Link width: 16X
[   372.276] (--) NVIDIA(GPU-1): DFP-0: disconnected
[   372.276] (--) NVIDIA(GPU-1): DFP-0: Internal DisplayPort
[   372.276] (--) NVIDIA(GPU-1): DFP-0: 2670.0 MHz maximum pixel clock
[   372.276] (--) NVIDIA(GPU-1):
[   372.277] (--) NVIDIA(GPU-1): DFP-1: disconnected
[   372.277] (--) NVIDIA(GPU-1): DFP-1: Internal TMDS
[   372.277] (--) NVIDIA(GPU-1): DFP-1: 165.0 MHz maximum pixel clock
[   372.277] (--) NVIDIA(GPU-1):
[   372.277] (--) NVIDIA(GPU-1): DFP-2: disconnected
[   372.277] (--) NVIDIA(GPU-1): DFP-2: Internal DisplayPort
[   372.277] (--) NVIDIA(GPU-1): DFP-2: 2670.0 MHz maximum pixel clock
[   372.277] (--) NVIDIA(GPU-1):
[   372.277] (--) NVIDIA(GPU-1): DFP-3: disconnected
[   372.277] (--) NVIDIA(GPU-1): DFP-3: Internal TMDS
[   372.277] (--) NVIDIA(GPU-1): DFP-3: 165.0 MHz maximum pixel clock
[   372.277] (--) NVIDIA(GPU-1):
[   372.277] (--) NVIDIA(GPU-1): DFP-4: disconnected
[   372.277] (--) NVIDIA(GPU-1): DFP-4: Internal DisplayPort
[   372.277] (--) NVIDIA(GPU-1): DFP-4: 2670.0 MHz maximum pixel clock
[   372.277] (--) NVIDIA(GPU-1):
[   372.375] (--) NVIDIA(GPU-1): Tech Concepts 75R635 (DFP-5): connected
[   372.375] (--) NVIDIA(GPU-1): Tech Concepts 75R635 (DFP-5): Internal TMDS
[   372.375] (--) NVIDIA(GPU-1): Tech Concepts 75R635 (DFP-5): 165.0 MHz maximum pixel clock
[   372.375] (--) NVIDIA(GPU-1):
[   372.375] (--) NVIDIA(GPU-1): DFP-6: disconnected
[   372.375] (--) NVIDIA(GPU-1): DFP-6: Internal DisplayPort
[   372.375] (--) NVIDIA(GPU-1): DFP-6: 2670.0 MHz maximum pixel clock
[   372.375] (--) NVIDIA(GPU-1):
[   372.375] (--) NVIDIA(GPU-1): DFP-7: disconnected
[   372.375] (--) NVIDIA(GPU-1): DFP-7: Internal TMDS
[   372.375] (--) NVIDIA(GPU-1): DFP-7: 165.0 MHz maximum pixel clock
[   372.375] (--) NVIDIA(GPU-1):
[   372.459] (II) NVIDIA(G0): Validated MetaModes:
[   372.459] (II) NVIDIA(G0):     "NULL"
[   372.459] (II) NVIDIA(G0): Virtual screen size determined to be 640 x 480
[   372.794] (++) NVIDIA(G0): DPI set to (96, 96); computed from -dpi X commandline option
[   372.794] (EE) Screen(s) found, but none have a usable configuration.
[   372.794] (EE)
Fatal server error:
[   372.794] (EE) no screens found(EE)
[   372.794] (EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[   372.794] (EE) Please also check the log file at "/var/log/Xorg.55.log" for additional information.
[   372.794] (EE)
[   372.794] (EE) Server terminated with error (1). Closing log file.




Build: [2023-06-24 03:10:18] [master] [6a2d55196b5253fef520ca883391d783716b4d06]

[ /etc/cont-init.d/10-setup_user.sh: executing... ]
**** Configure default user ****
Setting default user uid=1000(default) gid=1000(default)
usermod: no changes
Adding default user to video, audio, input and pulse groups
Adding default user to any additional required device groups
Adding user 'default' to group: 'user-gid-994' for device: /dev/input/event0
Adding user 'default' to group: 'user-gid-985' for device: /dev/dri/card0
Adding user 'default' to group: 'user-gid-989' for device: /dev/dri/renderD128
Setting umask to 000
Create the user XDG_RUNTIME_DIR path '/tmp/.X11-unix/run'
Adding default home directory template
Setting ownership of all log files in '/home/default/.cache/log'
Setting root password
Setting user password
DONE

[ /etc/cont-init.d/20-configre_sshd.sh: executing... ]
**** Configure SSH server ****
Disable SSH server
DONE

[ /etc/cont-init.d/30-configure_dbus.sh: executing... ]
**** Configure container dbus ****
Container configured to run its own dbus
DONE

[ /etc/cont-init.d/30-configure_udev.sh: executing... ]
**** Configure container to run udev management ****
**** Ensure the default user has permission to r/w on input devices ****
DONE

[ /etc/cont-init.d/40-setup_locale.sh: executing... ]
**** Locales already set correctly to en_US.UTF-8 UTF-8 ****
DONE

[ /etc/cont-init.d/50-configure_pulseaudio.sh: executing... ]
**** Configure pulseaudio ****
Configure pulseaudio to pipe audio to a socket
DONE

[ /etc/cont-init.d/60-configure_gpu_driver.sh: executing... ]
**** Found NVIDIA device 'NVIDIA RTX A2000' ****
Installing NVIDIA driver v535.54.03 to match what is running on the host
**** No Intel device found ****
**** No Intel device found ****
**** No AMD device found ****
DONE

[ /etc/cont-init.d/70-configure_xorg.sh: executing... ]
**** Generate NVIDIA xorg.conf ****
Configure Xwrapper.config
Configure container as primary the X server
Enabling evdev input class on pointers, keyboards, touchpads, touch screens, etc.
'/usr/share/X11/xorg.conf.d/10-evdev.conf' -> '/etc/X11/xorg.conf.d/10-evdev.conf'
Configuring X11 with GPU ID: 'GPU-d5495a99-109e-5f19-05d9-d718f1b35596'
Configuring X11 with PCI bus ID: 'PCI:129:0:0'
Writing X11 config with Modeline "1920x1080R"  138.50  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync

WARNING: Unable to locate/open X configuration file.

Package xorg-server was not found in the pkg-config search path.
Perhaps you should add the directory containing `xorg-server.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xorg-server' found
Option "ProbeAllGpus" "False" added to Screen "Screen0".
Option "AllowEmptyInitialConfiguration" "True" added to Screen "Screen0".
New X configuration file written to '/etc/X11/xorg.conf'

DONE

[ /etc/cont-init.d/80-configure-dind.sh: executing... ]
**** Configure Dockerd ****
Enable Dockerd daemon
Add user 'default' to docker group for sudoless execution
DONE

[ /etc/cont-init.d/90-configure_neko.sh: executing... ]
**** Configure Neko ****
Disable Neko server
DONE

[ /etc/cont-init.d/90-configure_sunshine.sh: executing... ]
**** Configure Sunshine ****
Enable Sunshine server
DONE

[ /etc/cont-init.d/90-configure_vnc.sh: executing... ]
**** Configure VNC ****
Configure VNC service port '32036'
Configure noVNC service port '32037'
Configure audio websocket port '32038'
Configure pulseaudio encoded stream port '32039'
Enable VNC server
Patching noVNC with audio websocket
DONE

[ /etc/cont-init.d/95-configure_secondary.sh: executing... ]
DONE

**** Starting supervisord ****
Logging all root services to '/var/log/supervisor/'
Logging all user services to '/home/default/.cache/log/'

2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/dbus.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/desktop.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/dind.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/neko.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/pulseaudio.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/sshd.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/steam.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/sunshine.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/udev.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/vnc-audio.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/vnc.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/xorg.ini" during parsing
2023-06-24 05:53:55,765 INFO Included extra file "/etc/supervisor.d/xvfb.ini" during parsing
2023-06-24 05:53:55,765 INFO Set uid to user 0 succeeded
2023-06-24 05:53:55,768 INFO RPC interface 'supervisor' initialized
2023-06-24 05:53:55,768 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-06-24 05:53:55,768 INFO supervisord started with pid 1
2023-06-24 05:53:56,770 INFO spawned: 'dbus' with pid 391
2023-06-24 05:53:56,771 INFO spawned: 'udev' with pid 392
2023-06-24 05:53:56,772 INFO spawned: 'dind' with pid 393
2023-06-24 05:53:56,773 INFO spawned: 'xorg' with pid 394
2023-06-24 05:53:56,774 INFO spawned: 'audiostream' with pid 395
2023-06-24 05:53:56,776 INFO spawned: 'novnc' with pid 396
2023-06-24 05:53:56,777 INFO spawned: 'pulseaudio' with pid 397
2023-06-24 05:53:56,779 INFO spawned: 'vncproxy' with pid 399
2023-06-24 05:53:56,780 INFO spawned: 'x11vnc' with pid 400
2023-06-24 05:53:56,781 INFO spawned: 'audiowebsock' with pid 402
2023-06-24 05:53:56,782 INFO spawned: 'desktop' with pid 404
2023-06-24 05:53:56,784 INFO spawned: 'sunshine' with pid 406
2023-06-24 05:53:56,784 INFO success: vncproxy entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
PULSEAUDIO: Starting pulseaudio service
2023-06-24 05:53:56,820 INFO reaped unknown pid 433 (exit status 0)
2023-06-24 05:53:57,809 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,809 INFO success: udev entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,809 INFO success: dind entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,809 INFO success: xorg entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,809 INFO success: audiostream entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,809 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,810 INFO success: pulseaudio entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,810 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,810 INFO success: audiowebsock entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,810 INFO success: desktop entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:57,810 INFO success: sunshine entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:53:59,802 INFO exited: xorg (exit status 1; not expected)
2023-06-24 05:54:00,804 INFO spawned: 'xorg' with pid 1053
2023-06-24 05:54:01,803 INFO success: xorg entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:54:01,815 INFO exited: xorg (exit status 1; not expected)
2023-06-24 05:54:01,820 INFO spawned: 'xorg' with pid 1062
2023-06-24 05:54:02,833 INFO success: xorg entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:54:02,833 INFO exited: xorg (exit status 1; not expected)
2023-06-24 05:54:03,836 INFO spawned: 'xorg' with pid 1085
2023-06-24 05:54:04,849 INFO success: xorg entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:54:04,903 INFO exited: xorg (exit status 1; not expected)
2023-06-24 05:54:05,906 INFO spawned: 'xorg' with pid 1105
2023-06-24 05:54:06,931 INFO success: xorg entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-24 05:54:06,955 INFO exited: xorg (exit status 1; not expected)
```

**Comment by kevinpastor** [comment]
I've been getting the same issue on a GTX 1050 Ti.

Xorg fails right on startup and keeps trying to start indefinitely. Here's the relevant content of the docker logs:

```txt
2023-06-25 09:45:09,259 INFO supervisord started with pid 1
2023-06-25 09:45:10,263 INFO spawned: 'dbus' with pid 320
2023-06-25 09:45:10,265 INFO spawned: 'udev' with pid 321
2023-06-25 09:45:10,268 INFO spawned: 'dind' with pid 322
2023-06-25 09:45:10,272 INFO spawned: 'xorg' with pid 323
2023-06-25 09:45:10,275 INFO spawned: 'pulseaudio' with pid 326
2023-06-25 09:45:10,281 INFO spawned: 'desktop' with pid 328
PULSEAUDIO: Starting pulseaudio service
2023-06-25 09:45:10,308 INFO exited: dind (exit status 4; not expected)
2023-06-25 09:45:11,310 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-25 09:45:11,310 INFO success: udev entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-25 09:45:11,314 INFO spawned: 'dind' with pid 359
2023-06-25 09:45:11,314 INFO success: xorg entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-25 09:45:11,314 INFO success: pulseaudio entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-25 09:45:11,314 INFO success: desktop entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-25 09:45:11,315 INFO reaped unknown pid 346 (exit status 0)
2023-06-25 09:45:13,298 INFO success: dind entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-25 09:45:15,371 INFO exited: xorg (exit status 1; not expected)
2023-06-25 09:45:15,374 INFO spawned: 'xorg' with pid 484
```

Looking at its log, we can deduce it's a problem with the NVIDIA configuration. Here's the relevant content of `/var/log/Xorg.55.log`:

```txt
[603961.191] (**) NVIDIA(0): Depth 24, (--) framebuffer bpp 32
[603961.191] (==) NVIDIA(0): RGB weight 888
[603961.191] (==) NVIDIA(0): Default visual is TrueColor
[603961.191] (==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[603961.191] (**) NVIDIA(0): Option "ModeValidation" "NoMaxPClkCheck, NoEdidMaxPClkCheck, NoMaxSizeCheck, NoHorizSyncCheck, NoVertRefreshCheck, NoVirtualSizeCheck, NoExtendedGpuCapabilitiesCheck, NoTotalSizeCheck, NoDualLinkDVICheck, NoDisplayPortBandwidthCheck, AllowNon3DVisionModes, AllowNonHDMI3DModes, AllowNonEdidModes, NoEdidHDMI2Check, AllowDpInterlaced"
[603961.191] (**) NVIDIA(0): Option "ProbeAllGpus" "False"
[603961.191] (**) NVIDIA(0): Option "AllowEmptyInitialConfiguration" "True"
[603961.191] (**) NVIDIA(0): Option "ConnectedMonitor" "DFP"
[603961.191] (**) NVIDIA(0): Enabling 2D acceleration
[603961.191] (**) NVIDIA(0): ConnectedMonitor string: "DFP"
[603961.191] (II) Loading sub module "glxserver_nvidia"
[603961.191] (II) LoadModule: "glxserver_nvidia"
[603961.191] (II) Loading /usr/lib/xorg/modules/extensions/libglxserver_nvidia.so
[603961.199] (II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
[603961.199]    compiled for 1.6.99.901, module version = 1.0.0
[603961.199]    Module class: X.Org Server Extension
[603961.199] (II) NVIDIA GLX Module  535.54.03  Tue Jun  6 22:23:41 UTC 2023
[603961.199] (II) NVIDIA: The X server supports PRIME Render Offload.
[603961.481] (--) NVIDIA(0): Valid display device(s) on GPU-0 at PCI:1:0:0
[603961.481] (--) NVIDIA(0):     DFP-0 (boot)
[603961.481] (--) NVIDIA(0):     DFP-1
[603961.481] (--) NVIDIA(0):     DFP-2
[603961.481] (--) NVIDIA(0):     DFP-3
[603961.482] (**) NVIDIA(0): Using ConnectedMonitor string "DFP-0".
[603961.482] (WW) NVIDIA: No DRM device: No direct render devices found.
[603961.482] (II) NVIDIA(0): NVIDIA GPU NVIDIA GeForce GTX 1050 Ti (GP107-A) at PCI:1:0:0
[603961.482] (II) NVIDIA(0):     (GPU-0)
[603961.482] (--) NVIDIA(0): Memory: 4194304 kBytes
[603961.482] (--) NVIDIA(0): VideoBIOS: 86.07.39.00.52
[603961.482] (II) NVIDIA(0): Detected PCI Express Link width: 16X
[603961.485] (--) NVIDIA(GPU-0): DFP-0: connected
[603961.485] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[603961.485] (--) NVIDIA(GPU-0): DFP-0: 330.0 MHz maximum pixel clock
[603961.485] (--) NVIDIA(GPU-0): 
[603961.485] (--) NVIDIA(GPU-0): DFP-1: disconnected
[603961.485] (--) NVIDIA(GPU-0): DFP-1: Internal TMDS
[603961.485] (--) NVIDIA(GPU-0): DFP-1: 165.0 MHz maximum pixel clock
[603961.485] (--) NVIDIA(GPU-0): 
[603961.485] (--) NVIDIA(GPU-0): DFP-2: disconnected
[603961.485] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[603961.485] (--) NVIDIA(GPU-0): DFP-2: 1440.0 MHz maximum pixel clock
[603961.485] (--) NVIDIA(GPU-0): 
[603961.485] (--) NVIDIA(GPU-0): DFP-3: disconnected
[603961.485] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[603961.485] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[603961.485] (--) NVIDIA(GPU-0): 
[603961.485] (**) NVIDIA(GPU-0): Mode Validation Overrides for DFP-0:
[603961.485] (**) NVIDIA(GPU-0):     NoMaxSizeCheck
[603961.485] (**) NVIDIA(GPU-0):     NoVirtualSizeCheck
[603961.485] (**) NVIDIA(GPU-0):     NoMaxPClkCheck
[603961.485] (**) NVIDIA(GPU-0):     NoEdidMaxPClkCheck
[603961.485] (**) NVIDIA(GPU-0):     NoHorizSyncCheck
[603961.485] (**) NVIDIA(GPU-0):     NoVertRefreshCheck
[603961.485] (**) NVIDIA(GPU-0):     NoExtendedGpuCapabilitiesCheck
[603961.485] (**) NVIDIA(GPU-0):     NoTotalSizeCheck
[603961.485] (**) NVIDIA(GPU-0):     NoDualLinkDVICheck
[603961.485] (**) NVIDIA(GPU-0):     NoDisplayPortBandwidthCheck
[603961.485] (**) NVIDIA(GPU-0):     AllowNon3DVisionModes
[603961.485] (**) NVIDIA(GPU-0):     AllowNonEdidModes
[603961.485] (**) NVIDIA(GPU-0):     AllowNonHDMI3DModes
[603961.485] (**) NVIDIA(GPU-0):     NoEdidHDMI2Check
[603961.485] (**) NVIDIA(GPU-0):     AllowDpInterlaced
[603961.486] (EE) NVIDIA(GPU-0): Unable to add conservative default mode "nvidia-auto-select".
[603961.486] (EE) NVIDIA(GPU-0): Unable to add "nvidia-auto-select" mode to ModePool.
[603961.486] (WW) NVIDIA(0): No valid modes for "DFP-0:1600x900R"; removing.
[603961.486] (WW) NVIDIA(0): No valid modes for "DFP-0:1600x900"; removing.
[603961.486] (WW) NVIDIA(0): 
[603961.486] (WW) NVIDIA(0): Unable to validate any modes; falling back to the default mode
[603961.487] (WW) NVIDIA(0):     "nvidia-auto-select".
[603961.487] (WW) NVIDIA(0): 
[603961.487] (WW) NVIDIA(0): No valid modes for "DFP-0:nvidia-auto-select"; removing.
[603961.487] (EE) NVIDIA(0): Unable to use default mode "nvidia-auto-select".
[603961.487] (EE) NVIDIA(0): Failing initialization of X screen
```

**Comment by sfxworks** [comment]
Just for reference, 
This works just fine with a VM and runc, but I don't think steam would use the gpu since it's missing the drivers...

I installed the nvidia-container-rutime https://aur.archlinux.org/packages/nvidia-container-runtime and tested that, same issue occurs.

**Comment by sfxworks** [comment]
I just did an update on the old machine. I can not start X on the old graphics card anymore with this.

**Comment by sfxworks** [comment]
Hmm, Nvidia had some driver updates

**Comment by sfxworks** [comment]
I can confirm that rolling back my driver to 530.41.03 works

```
Build: [2023-06-27 03:02:36] [master] [4896a5bc36f87548bb058bd9b1ed7dd430256a15]

[ /etc/cont-init.d/10-setup_user.sh: executing... ]
**** Configure default user ****
Setting default user uid=1000(default) gid=1000(default)
usermod: no changes
Adding default user to video, audio, input and pulse groups
Adding default user to any additional required device groups
Adding user 'default' to group: 'user-gid-994' for device: /dev/input/event0
Adding user 'default' to group: 'user-gid-985' for device: /dev/dri/card0
Adding user 'default' to group: 'user-gid-989' for device: /dev/dri/renderD128
Setting umask to 000
Create the user XDG_RUNTIME_DIR path '/tmp/.X11-unix/run'
Adding default home directory template
Setting ownership of all log files in '/home/default/.cache/log'
Setting root password
Setting user password
DONE

[ /etc/cont-init.d/20-configre_sshd.sh: executing... ]
**** Configure SSH server ****
Disable SSH server
DONE

[ /etc/cont-init.d/30-configure_dbus.sh: executing... ]
**** Configure container dbus ****
Container configured to run its own dbus
DONE

[ /etc/cont-init.d/30-configure_udev.sh: executing... ]
**** Configure container to run udev management ****
**** Ensure the default user has permission to r/w on input devices ****
DONE

[ /etc/cont-init.d/40-setup_locale.sh: executing... ]
**** Locales already set correctly to en_US.UTF-8 UTF-8 ****
DONE

[ /etc/cont-init.d/50-configure_pulseaudio.sh: executing... ]
**** Configure pulseaudio ****
Configure pulseaudio to pipe audio to a socket
DONE

[ /etc/cont-init.d/60-configure_gpu_driver.sh: executing... ]
**** Found NVIDIA device 'NVIDIA GeForce GTX 1070' ****
Downloading driver v530.41.03
/tmp/NVIDIA.run     100%[===================>] 328.36M  23.7MB/s    in 11s     
Installing NVIDIA driver v530.41.03 to match what is running on the host
**** No Intel device found ****
**** No Intel device found ****
**** No AMD device found ****
DONE

[ /etc/cont-init.d/70-configure_xorg.sh: executing... ]
**** Generate NVIDIA xorg.conf ****
Configure Xwrapper.config
Configure container as primary the X server
Enabling evdev input class on pointers, keyboards, touchpads, touch screens, etc.
'/usr/share/X11/xorg.conf.d/10-evdev.conf' -> '/etc/X11/xorg.conf.d/10-evdev.conf'
cat: '/sys/class/drm/card*/status': No such file or directory
No monitors connected. Installing dummy xorg.conf
'/templates/xorg/xorg.dummy.conf' -> '/etc/X11/xorg.conf'
Configuring X11 with GPU ID: 'GPU-e529b6c9-77a5-1417-52e4-2a99a613103c'
Configuring X11 with PCI bus ID: 'PCI:36:0:0'
Writing X11 config with Modeline "1600x900R"   97.50  1600 1648 1680 1760  900 903 908 926 +hsync -vsync

WARNING: No Layout specified, constructing implicit layout section using screen "Default Screen".



WARNING: Unable to find CorePointer in X configuration; attempting to add new CorePointer section.


WARNING: The CorePointer device was not specified explicitly in the layout; using the first mouse device.



WARNING: Unable to find CoreKeyboard in X configuration; attempting to add new CoreKeyboard section.


WARNING: The CoreKeyboard device was not specified explicitly in the layout; using the first keyboard device.



Using X configuration file: "/etc/X11/xorg.conf".
Option "ProbeAllGpus" "False" added to Screen "Default Screen".
Option "AllowEmptyInitialConfiguration" "True" added to Screen "Default Screen".
Backed up file '/etc/X11/xorg.conf' as '/etc/X11/xorg.conf.nvidia-xconfig-original'
Backed up file '/etc/X11/xorg.conf' as '/etc/X11/xorg.conf.backup'
New X configuration file written to '/etc/X11/xorg.conf'

DONE

[ /etc/cont-init.d/80-configure-dind.sh: executing... ]
**** Configure Dockerd ****
Enable Dockerd daemon
Add user 'default' to docker group for sudoless execution
DONE

[ /etc/cont-init.d/90-configure_neko.sh: executing... ]
**** Configure Neko ****
Disable Neko server
DONE

[ /etc/cont-init.d/90-configure_sunshine.sh: executing... ]
**** Configure Sunshine ****
Enable Sunshine server
DONE

[ /etc/cont-init.d/90-configure_vnc.sh: executing... ]
**** Configure VNC ****
Configure VNC service port '32036'
Configure noVNC service port '32037'
Configure audio websocket port '32038'
Configure pulseaudio encoded stream port '32039'
Enable VNC server
Patching noVNC with audio websocket
DONE

[ /etc/cont-init.d/95-configure_secondary.sh: executing... ]
DONE

**** Starting supervisord ****
Logging all root services to '/var/log/supervisor/'
Logging all user services to '/home/default/.cache/log/'

2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/dbus.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/desktop.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/dind.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/neko.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/pulseaudio.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/sshd.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/steam.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/sunshine.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/udev.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/vnc-audio.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/vnc.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/xorg.ini" during parsing
2023-06-27 02:51:08,766 INFO Included extra file "/etc/supervisor.d/xvfb.ini" during parsing
2023-06-27 02:51:08,766 INFO Set uid to user 0 succeeded
2023-06-27 02:51:08,768 INFO RPC interface 'supervisor' initialized
2023-06-27 02:51:08,768 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-06-27 02:51:08,769 INFO supervisord started with pid 1
2023-06-27 02:51:09,771 INFO spawned: 'dbus' with pid 376
2023-06-27 02:51:09,772 INFO spawned: 'udev' with pid 377
2023-06-27 02:51:09,772 INFO spawned: 'dind' with pid 378
2023-06-27 02:51:09,773 INFO spawned: 'xorg' with pid 379
2023-06-27 02:51:09,774 INFO spawned: 'audiostream' with pid 380
2023-06-27 02:51:09,775 INFO spawned: 'novnc' with pid 381
2023-06-27 02:51:09,776 INFO spawned: 'pulseaudio' with pid 382
2023-06-27 02:51:09,777 INFO spawned: 'vncproxy' with pid 383
2023-06-27 02:51:09,779 INFO spawned: 'x11vnc' with pid 385
2023-06-27 02:51:09,780 INFO spawned: 'audiowebsock' with pid 387
2023-06-27 02:51:09,781 INFO spawned: 'desktop' with pid 388
2023-06-27 02:51:09,782 INFO spawned: 'sunshine' with pid 391
PULSEAUDIO: Starting pulseaudio service
2023-06-27 02:51:09,782 INFO success: vncproxy entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-06-27 02:51:09,815 INFO reaped unknown pid 423 (exit status 0)
2023-06-27 02:51:10,803 INFO success: dbus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,803 INFO success: udev entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,803 INFO success: dind entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,803 INFO success: xorg entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,803 INFO success: audiostream entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,804 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,804 INFO success: pulseaudio entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,804 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,804 INFO success: audiowebsock entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,804 INFO success: desktop entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:10,804 INFO success: sunshine entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-27 02:51:12,208 INFO reaped unknown pid 942 (exit status 1)

```

**Comment by kevinpastor** [comment]
I can confirm that downgrading the Nvidia driver from v535.54.03 to v530.41.03 did the trick for me too with a GTX 1050 Ti.

I feel like it is still just a workaround for some underlying issue.

**Comment by HarmonyTechLabs** [comment]
Downgrading worked for me as well, I had to restrict nvidia drivers on arch to prevent upgrades.

**Comment by cravev** [comment]
I'm still experiencing Xorg failing on startup when using driver v530.41.03 on a GTX 1080ti. Xorg and x11vnc just get caught in a constant loop of starting and exiting with error code 1.

**Comment by Shadow229** [comment]
Searched everywhere for why this wasnt working! Downgrade to 350.41.03 worked with my Geforce 1660 Ti too

**Comment by Josh5** [comment]
Should be now fixed in latest build. Re-open this issue if it is not.

**Comment by kevinpastor** [comment]
Does work for me. Thanks!

**Comment by cravev** [comment]
Still failing to start Xorg. Seeing in the Xorg logs under '/home/default/.cache/log' that it's failing because "(EE) no screens found(EE)". Since this is headless, what screen would it be looking for?

`(II) NIDIA(0): NVIDIA GPU NVIDIA GeForce GTX 1080 Ti (GP102-A) at PCI: 7:0:0
II) NVIDIA(0) :
(GPU-0)
-) NVIDIA (0) : Memory: 11534336 kBytes (--) NVIDIA(0): VideoBIOS: 86.02.40.00.1a
(II) NVIDIA (0): Detected PCI Express Link width: 16X (EF) NVIDIA (GPU-0): Failed to acquire modesetting permission.
(EE) NVIDIA(0): Failing initialization of X screen
(II) Unloading gixserver nvidia
(EE) Screen(s) found, but none have a usable configuration.
（EE）
Fatal server error:
(EE) no screens found (EE)
(EE）
Please consult the The X.Org Foundation support
at http://wiki.x.org
for help.
(EE) Please also check the log file at "/var/log/Xorg.55.log" for additional information.
（EE）
(EE) Server terminated with error (1). Closing log file.`

**Comment by Josh5** [comment]
I've tested this on Unraid v6.11.5 with NVIDIA Driver v535.54.03, Intel 11th Gen and RTX 2060 with no monitor or dummy plug connected. And im getting fine results. I wonder if the older gtx worked a different way.

**Comment by HarmonyTechLabs** [comment]
@cravev in your .env file try adding the following and see if it fixes it for you:

`DISPLAY_VIDEO_PORT='dp-0'`

**Comment by cravev** [comment]
I may just be dumb. Had an Xorg server running on the base Arch install for a GUI desktop and that was causing the docker Xorg to not start I believe. I have it working now, albeit I have no desktop but I barely was using that anyway. Thanks @HarmonyTechLabs !!
